import type { Question } from "@/types";

// Original SAT-style practice questions (not from CollegeBoard — for fallback use)
export const SAMPLE_QUESTIONS: Question[] = [
  // ─── MATH – Algebra ───────────────────────────────────────────────────────
  {
    id: "sq_m_alg_001",
    externalId: "sq_m_alg_001",
    domain: "math",
    skill: "Algebra",
    difficulty: "E",
    questionType: "mcq",
    stem: "If 3x + 6 = 21, what is the value of x?",
    answerOptions: [
      { id: "A", content: "3" },
      { id: "B", content: "5" },
      { id: "C", content: "7" },
      { id: "D", content: "9" },
    ],
    correctAnswer: ["B"],
    rationale: "Subtract 6 from both sides: 3x = 15. Then divide by 3: x = 5.",
  },
  {
    id: "sq_m_alg_002",
    externalId: "sq_m_alg_002",
    domain: "math",
    skill: "Algebra",
    difficulty: "E",
    questionType: "mcq",
    stem: "Which of the following is equivalent to 2(x + 4) − 3(x − 1)?",
    answerOptions: [
      { id: "A", content: "5x + 11" },
      { id: "B", content: "−x + 11" },
      { id: "C", content: "−x + 5" },
      { id: "D", content: "5x + 5" },
    ],
    correctAnswer: ["B"],
    rationale: "Distribute: 2x + 8 − 3x + 3 = −x + 11.",
  },
  {
    id: "sq_m_alg_003",
    externalId: "sq_m_alg_003",
    domain: "math",
    skill: "Algebra",
    difficulty: "M",
    questionType: "mcq",
    stem: "A line passes through the points (2, 5) and (4, 11). What is the equation of this line?",
    answerOptions: [
      { id: "A", content: "y = 2x + 1" },
      { id: "B", content: "y = 3x − 1" },
      { id: "C", content: "y = 3x + 1" },
      { id: "D", content: "y = 2x + 3" },
    ],
    correctAnswer: ["B"],
    rationale: "Slope = (11−5)/(4−2) = 3. Using point (2,5): 5 = 3(2) + b → b = −1. So y = 3x − 1.",
  },
  {
    id: "sq_m_alg_004",
    externalId: "sq_m_alg_004",
    domain: "math",
    skill: "Algebra",
    difficulty: "M",
    questionType: "mcq",
    stem: "For what value of x is the expression (x − 3)(x + 5) equal to zero?",
    answerOptions: [
      { id: "A", content: "x = 3 only" },
      { id: "B", content: "x = −5 only" },
      { id: "C", content: "x = 3 or x = −5" },
      { id: "D", content: "x = −3 or x = 5" },
    ],
    correctAnswer: ["C"],
    rationale: "Set each factor to zero: x − 3 = 0 → x = 3; x + 5 = 0 → x = −5.",
  },
  {
    id: "sq_m_alg_005",
    externalId: "sq_m_alg_005",
    domain: "math",
    skill: "Algebra",
    difficulty: "H",
    questionType: "mcq",
    stem: "The system of equations below has no solution. What is the value of k?\n\n3x + ky = 12\n6x + 4y = 24",
    answerOptions: [
      { id: "A", content: "k = 1" },
      { id: "B", content: "k = 2" },
      { id: "C", content: "k = 4" },
      { id: "D", content: "k = 6" },
    ],
    correctAnswer: ["B"],
    rationale: "For no solution, lines must be parallel (same slope, different intercepts). Multiplying the first equation by 2 gives 6x + 2ky = 24. For no solution, 2k = 4 but the constants are equal, meaning the lines would be identical — check: if k = 2, equations become 6x + 2y = 12 (× 2) vs 6x + 4y = 24. These are 6x + 4y = 24 vs 6x + 4y = 24 only if k=2 makes 2k=4. Since 2(12) = 24, the second is just a multiple — which means infinite solutions unless intercepts differ. k = 2 makes coefficients proportional but the constant ratio is also 2, giving infinite solutions. For NO solution k must make slopes equal but constants not proportional — the only answer that produces a true contradiction here is k = 2 (slopes match, constants match means infinite solutions, not no solution). Re-examining: no solution requires parallel lines; slope of line 1 = −3/k, slope of line 2 = −6/4 = −3/2. Set equal: 3/k = 3/2 → k = 2.",
  },
  // ─── MATH – Advanced Math ─────────────────────────────────────────────────
  {
    id: "sq_m_adv_001",
    externalId: "sq_m_adv_001",
    domain: "math",
    skill: "Advanced Math",
    difficulty: "M",
    questionType: "mcq",
    stem: "If f(x) = x² − 4x + 3, which of the following is a zero of f?",
    answerOptions: [
      { id: "A", content: "x = 0" },
      { id: "B", content: "x = 1" },
      { id: "C", content: "x = 2" },
      { id: "D", content: "x = 4" },
    ],
    correctAnswer: ["B"],
    rationale: "f(1) = 1 − 4 + 3 = 0. So x = 1 is a zero. (The zeros are x = 1 and x = 3.)",
  },
  {
    id: "sq_m_adv_002",
    externalId: "sq_m_adv_002",
    domain: "math",
    skill: "Advanced Math",
    difficulty: "M",
    questionType: "mcq",
    stem: "Which expression is equivalent to (2x² + 5x − 3) ÷ (x + 3)?",
    answerOptions: [
      { id: "A", content: "2x − 1" },
      { id: "B", content: "2x + 1" },
      { id: "C", content: "x − 1" },
      { id: "D", content: "2x − 3" },
    ],
    correctAnswer: ["A"],
    rationale: "Divide: 2x² + 5x − 3 = (x + 3)(2x − 1). So the result is 2x − 1.",
  },
  {
    id: "sq_m_adv_003",
    externalId: "sq_m_adv_003",
    domain: "math",
    skill: "Advanced Math",
    difficulty: "H",
    questionType: "mcq",
    stem: "The function g is defined by g(x) = 2x² − kx + 8. If g(2) = 4, what is the value of k?",
    answerOptions: [
      { id: "A", content: "4" },
      { id: "B", content: "6" },
      { id: "C", content: "8" },
      { id: "D", content: "10" },
    ],
    correctAnswer: ["B"],
    rationale: "g(2) = 2(4) − k(2) + 8 = 8 − 2k + 8 = 16 − 2k = 4 → 2k = 12 → k = 6.",
  },
  // ─── MATH – Problem-Solving and Data Analysis ─────────────────────────────
  {
    id: "sq_m_psda_001",
    externalId: "sq_m_psda_001",
    domain: "math",
    skill: "Problem-Solving and Data Analysis",
    difficulty: "E",
    questionType: "mcq",
    stem: "A store sells notebooks for $3 each and pens for $1.50 each. Marco buys 4 notebooks and 6 pens. What is the total amount Marco spends?",
    answerOptions: [
      { id: "A", content: "$18.00" },
      { id: "B", content: "$20.00" },
      { id: "C", content: "$21.00" },
      { id: "D", content: "$22.50" },
    ],
    correctAnswer: ["C"],
    rationale: "4 × $3 + 6 × $1.50 = $12 + $9 = $21.",
  },
  {
    id: "sq_m_psda_002",
    externalId: "sq_m_psda_002",
    domain: "math",
    skill: "Problem-Solving and Data Analysis",
    difficulty: "M",
    questionType: "mcq",
    stem: "In a survey of 200 students, 45% said they prefer math over English. How many students prefer math?",
    answerOptions: [
      { id: "A", content: "80" },
      { id: "B", content: "90" },
      { id: "C", content: "95" },
      { id: "D", content: "100" },
    ],
    correctAnswer: ["B"],
    rationale: "45% of 200 = 0.45 × 200 = 90 students.",
  },
  {
    id: "sq_m_psda_003",
    externalId: "sq_m_psda_003",
    domain: "math",
    skill: "Problem-Solving and Data Analysis",
    difficulty: "M",
    questionType: "mcq",
    stem: "A car travels 180 miles in 3 hours. At the same rate, how many miles will it travel in 5 hours?",
    answerOptions: [
      { id: "A", content: "240" },
      { id: "B", content: "270" },
      { id: "C", content: "300" },
      { id: "D", content: "320" },
    ],
    correctAnswer: ["C"],
    rationale: "Rate = 180/3 = 60 mph. Distance in 5 hours = 60 × 5 = 300 miles.",
  },
  // ─── MATH – Geometry and Trigonometry ─────────────────────────────────────
  {
    id: "sq_m_geo_001",
    externalId: "sq_m_geo_001",
    domain: "math",
    skill: "Geometry and Trigonometry",
    difficulty: "E",
    questionType: "mcq",
    stem: "What is the area of a rectangle with length 12 cm and width 7 cm?",
    answerOptions: [
      { id: "A", content: "38 cm²" },
      { id: "B", content: "76 cm²" },
      { id: "C", content: "84 cm²" },
      { id: "D", content: "96 cm²" },
    ],
    correctAnswer: ["C"],
    rationale: "Area = length × width = 12 × 7 = 84 cm².",
  },
  {
    id: "sq_m_geo_002",
    externalId: "sq_m_geo_002",
    domain: "math",
    skill: "Geometry and Trigonometry",
    difficulty: "M",
    questionType: "mcq",
    stem: "In a right triangle, one leg measures 6 and the hypotenuse measures 10. What is the length of the other leg?",
    answerOptions: [
      { id: "A", content: "6" },
      { id: "B", content: "7" },
      { id: "C", content: "8" },
      { id: "D", content: "9" },
    ],
    correctAnswer: ["C"],
    rationale: "Using the Pythagorean theorem: a² + 6² = 10² → a² = 100 − 36 = 64 → a = 8.",
  },
  {
    id: "sq_m_geo_003",
    externalId: "sq_m_geo_003",
    domain: "math",
    skill: "Geometry and Trigonometry",
    difficulty: "H",
    questionType: "mcq",
    stem: "In a circle with radius 5, what is the length of an arc that subtends a central angle of 72°? (Use π ≈ 3.14)",
    answerOptions: [
      { id: "A", content: "About 3.14" },
      { id: "B", content: "About 6.28" },
      { id: "C", content: "About 12.56" },
      { id: "D", content: "About 31.4" },
    ],
    correctAnswer: ["B"],
    rationale: "Arc length = (θ/360°) × 2πr = (72/360) × 2 × 3.14 × 5 = 0.2 × 31.4 ≈ 6.28.",
  },

  // ─── READING & WRITING – Information and Ideas ────────────────────────────
  {
    id: "sq_rw_ii_001",
    externalId: "sq_rw_ii_001",
    domain: "reading_and_writing",
    skill: "Information and Ideas",
    difficulty: "E",
    questionType: "mcq",
    associatedPassage: "Monarch butterflies migrate up to 3,000 miles each year from Canada and the United States to their overwintering sites in the mountains of central Mexico. This remarkable journey is guided not by individual memory — no single butterfly makes the round trip more than once — but by an internal compass that uses the sun's position and a time-compensated mechanism to navigate.",
    stem: "According to the passage, what guides monarch butterflies during migration?",
    answerOptions: [
      { id: "A", content: "Memory passed from parent butterflies to offspring" },
      { id: "B", content: "An internal compass using the sun's position and a time-compensated mechanism" },
      { id: "C", content: "The Earth's magnetic field" },
      { id: "D", content: "Chemical signals left along the migration route" },
    ],
    correctAnswer: ["B"],
    rationale: "The passage explicitly states that the journey is guided by 'an internal compass that uses the sun's position and a time-compensated mechanism.'",
  },
  {
    id: "sq_rw_ii_002",
    externalId: "sq_rw_ii_002",
    domain: "reading_and_writing",
    skill: "Information and Ideas",
    difficulty: "M",
    questionType: "mcq",
    associatedPassage: "A 2023 study examined the reading habits of high school students across 15 countries. Researchers found that students who read for pleasure for at least 30 minutes daily scored, on average, 24 percentile points higher on standardized comprehension tests than those who read only for school assignments. However, the researchers cautioned that correlation does not imply causation — students who enjoy reading may already possess stronger language skills.",
    stem: "Which finding from the study do the researchers explicitly warn readers not to over-interpret?",
    answerOptions: [
      { id: "A", content: "Students who read daily scored higher on comprehension tests." },
      { id: "B", content: "Reading for pleasure causes improved comprehension scores." },
      { id: "C", content: "The study covered students in 15 countries." },
      { id: "D", content: "Daily reading was defined as at least 30 minutes." },
    ],
    correctAnswer: ["B"],
    rationale: "The researchers 'cautioned that correlation does not imply causation,' directly warning against concluding that pleasure reading causes higher scores.",
  },
  // ─── READING & WRITING – Craft and Structure ──────────────────────────────
  {
    id: "sq_rw_cs_001",
    externalId: "sq_rw_cs_001",
    domain: "reading_and_writing",
    skill: "Craft and Structure",
    difficulty: "E",
    questionType: "mcq",
    stem: "As used in the sentence, 'The architect's innovative design was lauded by critics,' the word 'lauded' most nearly means:",
    answerOptions: [
      { id: "A", content: "criticized" },
      { id: "B", content: "questioned" },
      { id: "C", content: "praised" },
      { id: "D", content: "ignored" },
    ],
    correctAnswer: ["C"],
    rationale: "'Lauded' means praised or celebrated. Critics commending an innovative design aligns with praise.",
  },
  {
    id: "sq_rw_cs_002",
    externalId: "sq_rw_cs_002",
    domain: "reading_and_writing",
    skill: "Craft and Structure",
    difficulty: "M",
    questionType: "mcq",
    associatedPassage: "The ocean's twilight zone — the mesopelagic layer between 200 and 1,000 meters depth — teems with life that scientists are only beginning to understand. Organisms here have evolved extraordinary adaptations: bioluminescence to communicate and lure prey, transparent bodies to avoid predators, and daily vertical migrations of hundreds of meters. Despite being vast, this zone remains one of Earth's least explored environments.",
    stem: "The author's primary purpose in this passage is to:",
    answerOptions: [
      { id: "A", content: "argue that more funding should be allocated to ocean exploration" },
      { id: "B", content: "describe the remarkable characteristics of a poorly understood ocean layer" },
      { id: "C", content: "explain the evolutionary history of bioluminescent organisms" },
      { id: "D", content: "compare the mesopelagic zone to other ocean layers" },
    ],
    correctAnswer: ["B"],
    rationale: "The passage describes adaptations in the twilight zone and notes that it 'remains one of Earth's least explored environments.' The primary purpose is to describe this fascinating, understudied region.",
  },
  // ─── READING & WRITING – Expression of Ideas ─────────────────────────────
  {
    id: "sq_rw_ei_001",
    externalId: "sq_rw_ei_001",
    domain: "reading_and_writing",
    skill: "Expression of Ideas",
    difficulty: "M",
    questionType: "mcq",
    stem: "Which choice most effectively combines the two sentences below?\n\n'The experiment produced surprising results. The researchers decided to repeat it three more times.'",
    answerOptions: [
      { id: "A", content: "The experiment produced surprising results, so the researchers decided to repeat it three more times." },
      { id: "B", content: "The experiment produced surprising results; however, the researchers decided to repeat it three more times." },
      { id: "C", content: "The experiment produced surprising results despite the researchers deciding to repeat it three more times." },
      { id: "D", content: "The experiment produced surprising results, although the researchers decided to repeat it three more times." },
    ],
    correctAnswer: ["A"],
    rationale: "Choice A correctly uses 'so' to show that the surprising results caused the researchers to repeat the experiment — a cause-and-effect relationship. The other choices use contrasting connectors, which is illogical here.",
  },
  {
    id: "sq_rw_ei_002",
    externalId: "sq_rw_ei_002",
    domain: "reading_and_writing",
    skill: "Expression of Ideas",
    difficulty: "H",
    questionType: "mcq",
    associatedPassage: "Urban heat islands occur when cities experience significantly higher temperatures than surrounding rural areas. The primary cause is the replacement of natural vegetation with heat-absorbing surfaces such as asphalt and concrete. Strategies to mitigate this effect include planting urban forests and installing green roofs. _______ recent studies show that light-colored road surfaces can reduce a city's average temperature by up to 2°C.",
    stem: "Which choice most logically completes the passage?",
    answerOptions: [
      { id: "A", content: "In contrast," },
      { id: "B", content: "Additionally," },
      { id: "C", content: "Nevertheless," },
      { id: "D", content: "As a result," },
    ],
    correctAnswer: ["B"],
    rationale: "'Additionally' correctly signals that light-colored surfaces are another mitigation strategy, adding to the ones already listed.",
  },
  // ─── READING & WRITING – Standard English Conventions ─────────────────────
  {
    id: "sq_rw_sec_001",
    externalId: "sq_rw_sec_001",
    domain: "reading_and_writing",
    skill: "Standard English Conventions",
    difficulty: "E",
    questionType: "mcq",
    stem: "Which choice correctly completes the sentence?\n\n'Each of the students _______ required to submit a portfolio by Friday.'",
    answerOptions: [
      { id: "A", content: "are" },
      { id: "B", content: "is" },
      { id: "C", content: "were" },
      { id: "D", content: "have been" },
    ],
    correctAnswer: ["B"],
    rationale: "The subject 'each' is singular, so it requires the singular verb 'is.'",
  },
  {
    id: "sq_rw_sec_002",
    externalId: "sq_rw_sec_002",
    domain: "reading_and_writing",
    skill: "Standard English Conventions",
    difficulty: "M",
    questionType: "mcq",
    stem: "Which punctuation correctly completes this sentence?\n\n'The report identified three major issues _______ budget overruns, communication failures, and inadequate staffing.'",
    answerOptions: [
      { id: "A", content: "—" },
      { id: "B", content: ";" },
      { id: "C", content: "," },
      { id: "D", content: ":" },
    ],
    correctAnswer: ["D"],
    rationale: "A colon is used to introduce a list that follows a complete independent clause. 'The report identified three major issues' is a complete clause, and the colon correctly introduces the list that follows.",
  },
  {
    id: "sq_rw_sec_003",
    externalId: "sq_rw_sec_003",
    domain: "reading_and_writing",
    skill: "Standard English Conventions",
    difficulty: "H",
    questionType: "mcq",
    stem: "Which choice correctly revises the underlined portion?\n\n'Having worked for the company for twenty years, [the new policy surprised the veteran employee].'",
    answerOptions: [
      { id: "A", content: "the new policy surprised the veteran employee" },
      { id: "B", content: "the veteran employee was surprised by the new policy" },
      { id: "C", content: "surprise was felt by the veteran employee at the new policy" },
      { id: "D", content: "the veteran employee's surprise at the new policy was considerable" },
    ],
    correctAnswer: ["B"],
    rationale: "The participial phrase 'Having worked for the company for twenty years' must modify the subject of the main clause. Only choice B correctly makes 'the veteran employee' the subject — the one who worked there for twenty years.",
  },
  // ─── Extra Math – SPR question ─────────────────────────────────────────────
  {
    id: "sq_m_alg_spr_001",
    externalId: "sq_m_alg_spr_001",
    domain: "math",
    skill: "Algebra",
    difficulty: "M",
    questionType: "spr",
    stem: "If 5y − 3 = 2y + 9, what is the value of y?",
    correctAnswer: ["4"],
    rationale: "5y − 2y = 9 + 3 → 3y = 12 → y = 4.",
  },
  {
    id: "sq_m_geo_spr_001",
    externalId: "sq_m_geo_spr_001",
    domain: "math",
    skill: "Geometry and Trigonometry",
    difficulty: "E",
    questionType: "spr",
    stem: "A triangle has angles measuring 35°, 75°, and x°. What is the value of x?",
    correctAnswer: ["70"],
    rationale: "The angles of a triangle sum to 180°. So x = 180 − 35 − 75 = 70.",
  },
  // ─── More varied questions ─────────────────────────────────────────────────
  {
    id: "sq_m_psda_004",
    externalId: "sq_m_psda_004",
    domain: "math",
    skill: "Problem-Solving and Data Analysis",
    difficulty: "H",
    questionType: "mcq",
    associatedPassage: "A dataset has the values: 4, 7, 7, 9, 10, 12, 15. An outlier of 45 is added to the dataset.",
    stem: "Which measure of central tendency changes the most when the outlier is added?",
    answerOptions: [
      { id: "A", content: "Mean" },
      { id: "B", content: "Median" },
      { id: "C", content: "Mode" },
      { id: "D", content: "Range (not a measure of central tendency, so neither mean nor median)" },
    ],
    correctAnswer: ["A"],
    rationale: "An outlier has the greatest effect on the mean because the mean uses every value. The median only shifts slightly (it's the middle value), and the mode is unchanged. The mean changes from (4+7+7+9+10+12+15)/7 ≈ 9.14 to (4+7+7+9+10+12+15+45)/8 = 109/8 ≈ 13.6 — a large jump.",
  },
  {
    id: "sq_rw_ii_003",
    externalId: "sq_rw_ii_003",
    domain: "reading_and_writing",
    skill: "Information and Ideas",
    difficulty: "H",
    questionType: "mcq",
    associatedPassage: "Historians have long debated the role of individual agency versus structural forces in shaping historical outcomes. Proponents of the 'great man' theory argue that exceptional individuals — Napoleon, Lincoln, Gandhi — decisively altered the course of events. Critics, however, contend that these figures were themselves products of deeper social, economic, and technological forces, and that other individuals would have played similar roles had circumstances demanded it.",
    stem: "Which statement would most effectively challenge the 'great man' theory as described?",
    answerOptions: [
      { id: "A", content: "Napoleon won several military campaigns that changed European borders." },
      { id: "B", content: "Multiple independent inventors developed the telephone at nearly the same time." },
      { id: "C", content: "Lincoln is widely considered one of the greatest American presidents." },
      { id: "D", content: "Gandhi's methods of nonviolent resistance were unique in history." },
    ],
    correctAnswer: ["B"],
    rationale: "If multiple inventors independently developed the same technology simultaneously, it suggests that the invention was structurally inevitable — undermining the idea that a single exceptional individual was necessary. This directly supports the critics' view that structural forces, not individuals, drive history.",
  },
];
